version: 2.1

# defining some anchors 
default_container: &def_container
  docker:
    - image: circleci/node:13.8.0

# defining some commands
commands:
  say_hello:
    description: Saying Hello in terminal
    parameters:
      to:
        type: string
        default: "world"
    steps:
      - run: echo hello << parameters.to >>

jobs:
  save_to_workspace:
    <<: *def_container
    # environment:
    #   PROJECT_URL: 'http'
    working_directory: ~/devops-project
    steps:
      - run:
          name: "printing working dir"
          command: pwd
      - say_hello:
          to: "from my world"
      
      
# list of workflows
workflows:
  default:
    jobs:
      - save_to_workspace





