version: 2.1

jobs:
  save_to_workspace:
    docker: 
      - image: circleci/node:13.8.0
    environment:
      PROJECT_URL: << pipeline.project.git_url >>/compare/lol
    steps:
      - run: echo '<< pipeline.id >> - {{ epoch }} - {{ .Environment.PROJECT_URL }}' > file.txt
      - run: pwd
      - run: ls ~/
  get_from_workspace:
    docker: 
      - image: circleci/node:13.8.0
    steps: []
# list of workflows
workflows:
  default:
    jobs:
      - save_to_workspace





