version: 2.1

# # reusable block of code
# commands:
#   command1:
#     description:
#     parameters:
#       workflow_id:
#         type: string
#       event:
#         type: string
#     steps: # - steps   

# 
jobs:
  print_hello:
    environment:
      P: lol
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: printing hello
          command: |
            echo "Hello "
  print_world:
    environment:
      P: lol2
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: printing world
          command: |
            echo "world!"

# list of workflows
# each has the order in which job should be running
workflows:
  default:
    jobs:
      - print_hello # ref
      - print_world:
          requires: [print_hello]





