version: 2.1

# defining some anchors 
default_container: &def_container
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *def_container
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages" 
          paths:
            - node-modules
  test:
    <<: *def_container
    steps:
      - checkout
      - restore_cache:
          keys: ['npm-packages']
      - run: npm i
  analyze:
    <<: *def_container
    steps:
      - checkout
      - restore_cache:
          keys: ['npm-packages']
      - run: npm audit
      
# list of workflows
workflows:
  simple:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]




