version: 2.1

# defining some anchors 
default_container: &def_container
  docker:
    - image: circleci/node:13.8.0

# defining some commands
commands:
  say_hello:
    description: Saying Hello in terminal
    parameters:
      to:
        type: string
        default: "world"
    steps:
      - run: echo hello << parameters.to >>

jobs:
  run_job:
    <<: *def_container
    working_directory: ~/devops-project
    steps:
      - run:
          name: "Return error"
          command: return 1
      - run:
          name: "A failure happened"
          command: echo "an error happened "
          when: on_fail 
          
      
# list of workflows
workflows:
  simple:
    jobs:
      - run_job





