version: 2.1

jobs:
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    environment:
      PROJECT_URL: << pipeline.project.git_url >>/compare/lol
    steps:
      - run: echo '<< pipeline.id >>'
      - run: echo $PROJECT_URL
  print_world:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

# list of workflows
workflows:
  default:
    jobs:
      - print_hello 





