version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
        command: pwd
      - run:
        command: ls -la
      - run:
          name: Create the infrastructure
          command: |
            aws cloudformation deploy \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --template-file template.yml \
              --region us-east-1
              
workflows:
  my_workflow:
    jobs:
      - create_infrastructure


    