Description: >
  CloudFormation Template to Deploy EC2 Instance inside of a specific VPC 
Parameters: 
  myVPCID:
      Description: VPC used to deploy our resources below
      Type: AWS::EC2::VPC::Id
  PublicSubnetID:
      Description: Subnet to be used for our Web Server
      Type: AWS::EC2::Subnet::Id
  AMIID:
      Description: AMI to use for our base image
      Type: String
Resources:
  webAccessSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref myVPCID
      GroupDescription: SecGroup that only allows inbound access on TCP port 80 and allows unrestricted outbound access
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: 
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIID
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - Ref: webAccessSecGroup
          SubnetId: !Ref PublicSubnetID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd

